# Site settings
title: Magnified Joy Photography
description: 
baseurl: ""
permalink: /:categories/:title/
url: "http://www.magnifiedjoy.com"
include: ['_css','_js','_img']
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
