# Site settings
title: M.Joy
description: 
baseurl: "/m.joy" 
permalink: /:categories/:title/
url: "http://code.lookitscook.com/m.joy" 
include: ['_css','_js']
gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
