# Site settings
title: M.Joy
email: matt@lookitscook.com
description: 
baseurl: "" 
permalink: /:categories/:title/
url: "http://code.lookitscook.com/m.joy" # the base hostname & protocol for your site
twitter_username: lookitscook
github_username:  lookitscook
gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
